Fix kotlin telegram bot issue #165:
kotlin-telegram-bot/kotlin-telegram-bot pull request #250
Opened 2022-06-30 18:15 UTC by martin-petersen

- Add the ability to specify text entities in several classes and methods

2022-07-02 20:12 UTC, seik commented
Thank you for tackling this!

Like with the other PR there are conflicts. There are also places were the variable is named `caption_entities` and others where it's `captionEntities`, camel case it's the preferred style.

2022-07-02 20:13 UTC, seik requested changes
Thank you for tackling this!

Like with the other PR there are conflicts. There are also places were the variable is named `caption_entities` and others where it's `captionEntities`, camel case it's the preferred style.

2022-07-15 12:29 UTC, martin-petersen reviewed
I have changed the occurrences of caption_entities to camel case and the conflicts are resolved

2026-05-14 12:13 UTC, seik commented
Hi @martin-petersen — thanks for the original PR. After several years the branch had drifted far past main, so I've started landing this incrementally: ce03795 adds `entities` to `sendMessage` / `editMessageText` and `captionEntities` to `editMessageCaption` (the highest-impact pieces of #165).

The remaining surface — `caption_entities` on `sendPhoto`/`sendVideo`/`sendAudio`/`sendDocument`/`sendAnimation`, plus the `InputMedia*` and `InlineQueryResult*` variants — is tracked separately as a follow-up issue. You're attributed as author on the commit. Really appreciate the original work — closing here.

2026-05-14 12:13 UTC, closed without merging